name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - pandas
  - jinja2
  - jsonpath-ng
  - networkx
  - lark
  - tabulate
  - os